package ship.f.engine.shared.utils.serverdrivenui2.config.state.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("ColorScheme2")
data class ColorScheme2(
    val primary: Long,
    val onPrimary: Long,
    val primaryContainer: Long,
    val onPrimaryContainer: Long,
    val inversePrimary: Long,
    val secondary: Long,
    val onSecondary: Long,
    val secondaryContainer: Long,
    val onSecondaryContainer: Long,
    val tertiary: Long,
    val onTertiary: Long,
    val tertiaryContainer: Long,
    val onTertiaryContainer: Long,
    val background: Long,
    val onBackground: Long,
    val surface: Long,
    val onSurface: Long,
    val surfaceVariant: Long,
    val onSurfaceVariant: Long,
    val surfaceTint: Long,
    val inverseSurface: Long,
    val inverseOnSurface: Long,
    val error: Long,
    val onError: Long,
    val errorContainer: Long,
    val onErrorContainer: Long,
    val outline: Long,
    val outlineVariant: Long,
    val scrim: Long,
    val surfaceBright: Long,
    val surfaceDim: Long,
    val surfaceContainer: Long,
    val surfaceContainerHigh: Long,
    val surfaceContainerHighest: Long,
    val surfaceContainerLow: Long,
    val surfaceContainerLowest: Long,
) {

    companion object {
        val DefaultLightColorScheme2 = ColorScheme2(
//            primary = 0xFFE64A19,
            primary = 0xFFea5a1c,
            onPrimary = 0xFFFFFFFF,
            secondary = 0xFF717680,
            onSecondary = 0xFFFFFFFF,
            onSecondaryContainer = 0xFF414651,
            secondaryContainer = 0xFFFFFFFF,
            background = 0xFFF9F9F9,
            onBackground = 0xFF1C1C1E,
            surface = 0xFFFFFFFF,
            onSurface = 0xFF1C1C1E,
            surfaceVariant = 0xFFF1F1F1,
            onSurfaceVariant = 0xFF6E6E6E,
            outline = 0xFFBDBDBD,
            outlineVariant = 0xFFBDBDBD,
            error = 0xFFFF0000,
            onError = 0xFFFFFFFF,
            primaryContainer = 0xFFFF00FF, // Not yet implemented,
            onPrimaryContainer = 0xFFFF00FF, // Not yet implemented,
            inversePrimary = 0xFFFF00FF, // Not yet implemented,
            tertiary = 0xFF3F3F3F,
            onTertiary = 0xFFFF00FF, // Not yet implemented,
            tertiaryContainer = 0xFF999999,
            onTertiaryContainer = 0xFFFF00FF, // Not yet implemented,
            surfaceTint = 0xFFFF00FF, // Not yet implemented,
            inverseSurface = 0xFF000000,
            inverseOnSurface = 0xFF000000, // Not yet implemented,
            errorContainer = 0xFFFF00FF, // Not yet implemented,
            onErrorContainer = 0xFFFF00FF, // Not yet implemented,
            scrim = 0xFFFF00FF, // Not yet implemented,
            surfaceBright = 0xFFFF00FF, // Not yet implemented,
            surfaceDim = 0xFFF4F4F4,
            surfaceContainer = 0xFFFF00FF, // Not yet implemented,
            surfaceContainerHigh = 0xFFFF00FF, // Not yet implemented,
            surfaceContainerHighest = 0xFFFF00FF, // Not yet implemented,
            surfaceContainerLow = 0xFFFF00FF, // Not yet implemented,
            surfaceContainerLowest = 0xFFFF00FF, // Not yet implemented,
        )

        val DefaultDarkColorScheme2 = ColorScheme2(
            primary = 0xFFea5a1c,
            onPrimary = 0xFFFFFFFF,
            secondary = 0xFF717680,
            onSecondary = 0xFFFFFFFF,
            onSecondaryContainer = 0xFF414651,
            secondaryContainer = 0xFFFFFFFF,
            background = 0xFFF9F9F9,
            onBackground = 0xFF1C1C1E,
            surface = 0xFFFFFFFF,
            onSurface = 0xFF1C1C1E,
            surfaceVariant = 0xFFF1F1F1,
            onSurfaceVariant = 0xFF6E6E6E,
            outline = 0xFFBDBDBD,
            outlineVariant = 0xFFBDBDBD,
            error = 0xFFFF0000,
            onError = 0xFFFFFFFF,
            primaryContainer = 0xFFFF00FF, // Not yet implemented,
            onPrimaryContainer = 0xFFFF00FF, // Not yet implemented,
            inversePrimary = 0xFFFF00FF, // Not yet implemented,
            tertiary = 0xFF3F3F3F,
            onTertiary = 0xFFFF00FF, // Not yet implemented,
            tertiaryContainer = 0xFF999999,
            onTertiaryContainer = 0xFFFF00FF, // Not yet implemented,
            surfaceTint = 0xFFFF00FF, // Not yet implemented,
            inverseSurface = 0xFF000000,
            inverseOnSurface = 0xFF000000, // Not yet implemented,
            errorContainer = 0xFFFF00FF, // Not yet implemented,
            onErrorContainer = 0xFFFF00FF, // Not yet implemented,
            scrim = 0xFFFF00FF, // Not yet implemented,
            surfaceBright = 0xFFFF00FF, // Not yet implemented,
            surfaceDim = 0xFFF4F4F4,
            surfaceContainer = 0xFFFF00FF, // Not yet implemented,
            surfaceContainerHigh = 0xFFFF00FF, // Not yet implemented,
            surfaceContainerHighest = 0xFFFF00FF, // Not yet implemented,
            surfaceContainerLow = 0xFFFF00FF, // Not yet implemented,
            surfaceContainerLowest = 0xFFFF00FF, // Not yet implemented,
        )
        
//        val DefaultDarkColorScheme2 = ColorScheme2(
//            primary = 0xFFea5a1c,
//            onPrimary = 0xFFFFFFFF,
//            secondary = 0xFF717680,
//            onSecondary = 0xFFFFFFFF,
//            onSecondaryContainer = 0xFF414651,
//            secondaryContainer = 0xFFFFFFFF,
//            background = 0xFF1E1E1E,
//            onBackground = 0xFFF1F1F1,
//            surface = 0xFF121212,
//            onSurface = 0xFFF1F1F1,
//            surfaceVariant = 0xFF2A2A2A,
//            onSurfaceVariant = 0xFFB0B0B0,
//            outline = 0xFF444444,
//            outlineVariant = 0xFFBDBDBD,
//            error = 0xFFFF0000,
//            onError = 0xFFFFFFFF,
//            primaryContainer = 0xFFFF00FF, // Not yet implemented,
//            onPrimaryContainer = 0xFFFF00FF, // Not yet implemented,
//            inversePrimary = 0xFFFF00FF, // Not yet implemented,
//            tertiary = 0xFFFF00FF, // Not yet implemented,
//            onTertiary = 0xFFFF00FF, // Not yet implemented,
//            tertiaryContainer = 0xFFFF00FF, // Not yet implemented,
//            onTertiaryContainer = 0xFFFF00FF, // Not yet implemented,
//            surfaceTint = 0xFFFF00FF, // Not yet implemented,
//            inverseSurface = 0xFFFF00FF, // Not yet implemented,
//            inverseOnSurface = 0xFFFF00FF, // Not yet implemented,
//            errorContainer = 0xFFFF00FF, // Not yet implemented,
//            onErrorContainer = 0xFFFF00FF, // Not yet implemented,
//            scrim = 0xFFFF00FF, // Not yet implemented,
//            surfaceBright = 0xFFFF00FF, // Not yet implemented,
//            surfaceDim = 0xFFFF00FF, // Not yet implemented,
//            surfaceContainer = 0xFFFF00FF, // Not yet implemented,
//            surfaceContainerHigh = 0xFFFF00FF, // Not yet implemented,
//            surfaceContainerHighest = 0xFFFF00FF, // Not yet implemented,
//            surfaceContainerLow = 0xFFFF00FF, // Not yet implemented,
//            surfaceContainerLowest = 0xFFFF00FF, // Not yet implemented,
//        )
    }
}